name: "Setup Jule environment"
description: "Use Jule on GitHub Actions"
author: "julelang"
branding:
  icon: code
  color: gray-dark
inputs:
  version:
    description: "The version of Jule that will be downloaded. Use \"latest\" for the latest stable release."
    required: true
    default: "latest"
  directory:
    description: "Directory where Jule will be downloaded."
    required: true
    default: "."
  add-to-path:
    description: "Whether to add Jule binaries to the PATH or not."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Adjust directory (UNIX-Like)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        if [[ "$RUNNER_OS" != "Windows" ]]; then
          directory="${{ inputs.directory }}"
          if [[ ${{ inputs.directory }} == */ ]]; then
            directory="${directory%?}"
          fi
        fi

        if [[ "$RUNNER_OS" == "Windows" ]]; then
          directory="${directory//\\//}"
        fi
        echo "DIRECTORY=$directory" >> $GITHUB_ENV
    - name: Adjust directory (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        if ($env:OS -eq "Windows_NT") {
          $directory = "${{ inputs.directory }}"
          if ($directory.EndsWith("/")) {
            $directory = $directory.Substring(0, $directory.Length - 1)
          }

          $directory = $directory -replace '\\', '/'
          echo "DIRECTORY=$directory" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        }
    - name: Install Jule
      shell: bash
      run: |
        os="-"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          os="windows"
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          os="darwin"
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          os="linux"
        else
          echo "unsupported operating system: ${RUNNER_OS}"
          exit 1
        fi
        arch="-"
        if [[ "$RUNNER_ARCH" == "X86" ]]; then
          arch="i386"
        elif [[ "$RUNNER_ARCH" == "X64" ]]; then
          arch="amd64"
        elif [[ "$RUNNER_ARCH" == "ARM64" ]]; then
          arch="arm64"
        else
          echo "unsupported architecture: ${RUNNER_ARCH}"
          exit 1
        fi
        target="${os}-${arch}"
        if [[ "$target" == "darwin-arm64" ]] || [[ "$target" == "darwin-amd64" ]]; then
          :
        elif [[ "$target" == "linux-arm64" ]] || [[ "$target" == "linux-amd64" ]] || [[ "$target" == "linux-i386" ]]; then
          :
        elif [[ "$target" == "windows-arm64" ]] || [[ "$target" == "windows-amd64" ]] || [[ "$target" == "windows-i386" ]]; then
          :
        else
          echo "unsupported target: ${target}"
        fi
        if [[ ${{ inputs.version }} == "dev" ]]; then
          bash <(curl -s https://raw.githubusercontent.com/julelang/julec-ir/main/compile-ir.sh)
        else
          version=${{ inputs.version }}
          if [[ ${{ inputs.version }} == "latest" ]] || [[ ${{ inputs.version }} == "current" ]]; then
            version="jule0.1.7"
          fi
          curl -L -o release.zip "https://github.com/julelang/jule/releases/download/$version/$version-$target.zip"
          unzip release.zip -d "$DIRECTORY"
        fi
    - name: Add Jule binaries to the PATH (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        if ('${{ inputs.add-to-path }}' -eq 'true') {
          echo "$env:DIRECTORY\jule\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        }
    - name: Add Jule binaries to the PATH (UNIX-Like)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        if [[ ${{ inputs.add-to-path }} == 'true' ]]; then
          echo "$DIRECTORY/jule/bin" >> "$GITHUB_PATH"
        fi
    - name: Version
      shell: bash
      run: |
        julec version
